### ISSUE TITLE
[Bug]: shortdoct does not get required under emacs verstion 29.0.50 with fshortdoc version 0.1.0

### ISSUE THREAD

**Issue by malcook** [rejeep/f.el#124] opened 2023-04-03 15:55 UTC
### Expected behavior

shortdoc should (presumably?) be required in emacs version 29.0.50 using f-shortdoc in elpa/f-20230116.1032, which shows:

;;; Version: 0.1.0

### Actual behavior

shortdoc is not required under emacs 29.0.50

I observed this due to resuling failing to compile of current elpa/citar 

### f.el version

something else (please specify)

### Emacs version

something else (please specify)

**Comment by Phundrak** [comment] 2023-04-03 19:42
This is the intended behaviour of f.el, Emacs 29 does not need to explicitly require shortdoc anymore. Emacs 29.0.50 is also not supported as it is an obsolete development version since late November 2022, you should either upgrade to Emacs 29.0.60 or Emacs 30.0.50.

Most likely a duplicate of #120.

**Closed by Phundrak** 2023-04-03 19:42 UTC
Labels: bug
