### ISSUE TITLE
f requires dash 2.2 but that does not yet exist

### ISSUE THREAD

**Issue by dingesista** [rejeep/f.el#94] opened 2018-11-23 07:29 UTC
Hi

Maybe I am misreading things, but I just noticed that Dash on elpa is at version: 2.12.0. However, f on melpa "Requires: dash-2.2.0".

I noticed this when running emacs -Q and package-initialize

Unable to activate package ‘f’.
Required package ‘dash-2.2.0’ is unavailable

When I run emacs (without the -Q) this does not seem to be a problem (and that is confusing).

**Comment by Phundrak** [comment] 2022-05-13 18:31
I cannot reproduce this issue, and `2.12.0` should be greater than `2.2.0` anyway (not to mention dash went to version `2.19.0` in the last four years).
```emacs-lisp
(version< "2.2.0" "2.12.0") ;; => t
```
With `emacs -Q`, I can execute the following without any issues:
``` emacs-lisp
(setq package-archives '(("melpa"  . "https://melpa.org/packages/")
                         ("gnu"    . "https://elpa.gnu.org/packages/")
                         ("nongnu" . "https://elpa.nongnu.org/nongnu/")))
(package-initialize)
(package-refresh-contents)
(package-install 'f)
```
Can anyone reproduce this error?

**Comment by Phundrak** [comment] 2022-05-31 21:49
Closing this issue, I’ll reopen it if someone runs into it again.

**Closed by Phundrak** 2022-05-31 21:49 UTC
